require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/HeredocIndentation:
  Exclude:
    - 'lib/hawksi.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'